version: '3.0'
services:
  "spring-camel-file-mover-service":
    image: "grantlee289/spring-camel-file-mover-service"
    volumes:
      - opt/apps/spring-camel-file-mover/logs:/logs
      - opt/apps/spring-camel-file-mover/from:/from
      - opt/apps/spring-camel-file-mover/to:/to
    restart: unless-stopped