version: '3.7'
services:
  spring-camel-file-mover:
    image: grantlee289/spring-camel-file-mover
    container_name: spring-camel-file-mover-app
    volumes:
      - /opt/apps/spring-camel-file-mover/logs:/logs
      - /opt/apps/spring-camel-file-mover/from:/from
      - /opt/apps/spring-camel-file-mover/to:/to
    restart: unless-stopped